### PR TITLE
Add change log support

### LINKED ISSUE #47: Add change log support
Add change log support

- [ ] Add an initial empty ChangeLog or almost empty file
- [ ] Create the ChangeLog.d with its 00README.md
- [ ] Adapt assemble_changelog.py to work for both mbedtls and psa-cryto repo
- [ ] Add check_changelog all.sh component

DOD: Same support for change logs in psa-crypto as in mbedtls

### PR DESCRIPTION
**Pull request by gabor-mezei-arm**
## Description

Add support to create an initial changelog entry if no entries found and specify the name of the project from the previous entries.

Resolve #47 

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required, only internal change
- [x] **backport** not required, new feature
- [x] **tests** not required, already exists

### CODE REVIEW

**Review by tom-daubney-arm — APPROVED** [review]
I think this is complete. LGTM - thanks

**Review by ronald-cron-arm — CHANGES_REQUESTED** [review]
Only one thing I would prefer to change.

**Review by ronald-cron-arm — APPROVED** [review]
LGTM, thanks.

**Review by tom-daubney-arm — APPROVED** [review]
LGTM.

**Pull request merged**
