### PR TITLE
Add IOP Key Agreement Key Exercises

### PR DESCRIPTION
**Pull request by paul-elliott-arm**
Key exercise tests for Interruptible Key Agreement.

Resolves https://github.com/Mbed-TLS/mbedtls/issues/9109

PR checklist
Please remove the segment/s on either side of the | symbol as appropriate, and add any relevant link/s to the end of the line.
If the provided content is part of the present PR remove the # symbol.

- [x] **changelog** provided | not required because: Part of interruptible ECC work
- [x] **development PR** provided https://github.com/Mbed-TLS/mbedtls/pull/9735
- [x] **framework PR** provided https://github.com/Mbed-TLS/mbedtls-framework/pull/82
- [x] **TF-PSA-Crypto PR** provided : this
- [x] **3.6 PR** ~~provided # |~~ not required because: New feature for 4.0
- [x] **2.28 PR** ~~provided # |~~ not required because: New feature for 4.0
- tests provided ~~| not required because:~~

### CODE REVIEW

**Review by waleed-elmelegy-arm — DISMISSED** [review]
LGTM.

**Review by yanesca — APPROVED** [review]
Did the split and arrived at the same content.

**Comment by paul-elliott-arm** [comment]
Updated framework pointer

**Review by waleed-elmelegy-arm — APPROVED** [review]
LGTM

**Review by yanesca — APPROVED** [review]
LGTM

**Pull request merged**
